language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
    - python setup.py install
script: python -m unittest discover
branches:
  only:
    - master
after_success:
  - bash <(curl -s https://codecov.io/bash)
